import { Lexend} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/nabar/Navbar";
import { Container } from '@mui/material';

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Code Optix Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Container className="container"  maxWidth='xl' elevation={0} disableGutters={true} >
          <Navbar/>
        {children}

        <Footer/>
        </Container>
     
        
        </body>
    </html>
  );
}
